name: ✨ Backend 기능 제안
description: 새로운 API 개발이나 서버 로직 개선을 제안합니다.
title: '[FEAT] '
labels: ['feat', 'backend']
body:
  - type: textarea
    id: description
    attributes:
      label: 기능 설명
      description: 제안하고자 하는 기능에 대해 상세히 설명해 주세요.
    validations:
      required: true
  - type: textarea
    id: logic
    attributes:
      label: 서버 로직 / DB 스키마 제안
      description: 생각하신 로직이나 변경될 DB 테이블 구조가 있다면 적어주세요.
  - type: textarea
    id: ref
    attributes:
      label: 참고 자료
      description: 참고할 만한 아티클이나 라이브러리 링크가 있다면 적어주세요.
