-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.landmark (
  contentid bigint NOT NULL,
  contenttypeid integer,
  title text NOT NULL,
  addr1 text,
  addr2 text,
  zipcode character varying,
  tel text,
  areacode integer,
  sigungucode integer,
  cat1 character varying,
  cat2 character varying,
  cat3 character varying,
  mapx double precision,
  mapy double precision,
  mlevel integer,
  firstimage text,
  firstimage2 text,
  cpyrhtdivcd character varying,
  createdtime timestamp without time zone,
  modifiedtime timestamp without time zone,
  ldongregncd integer,
  ldongsigngucd integer,
  lclssystm1 character varying,
  lclssystm2 character varying,
  lclssystm3 character varying,
  CONSTRAINT landmark_pkey PRIMARY KEY (contentid)
);
CREATE TABLE public.landmark_detail (
  contentid bigint NOT NULL,
  contenttypeid integer,
  title text NOT NULL,
  addr1 text,
  addr2 text,
  zipcode character varying,
  tel text,
  areacode integer,
  sigungucode integer,
  cat1 character varying,
  cat2 character varying,
  cat3 character varying,
  mapx double precision,
  mapy double precision,
  mlevel integer,
  firstimage text,
  firstimage2 text,
  cpyrhtdivcd character varying,
  createdtime timestamp without time zone,
  modifiedtime timestamp without time zone,
  ldongregncd integer,
  ldongsigngucd integer,
  lclssystm1 character varying,
  lclssystm2 character varying,
  lclssystm3 character varying,
  homepage text,
  overview text,
  CONSTRAINT landmark_detail_pkey PRIMARY KEY (contentid),
  CONSTRAINT landmark_detail_contentid_fk FOREIGN KEY (contentid) REFERENCES public.landmark(contentid)
);
CREATE TABLE public.landmark_image (
  id serial not null,
  contentid bigint not null,
  originimgurl text not null,
  imgname text not null,
  smallimageurl text null,
  cpyrhtdivcd character varying(10) null,
  serialnum character varying(20) null,
  constraint landmark_image_pkey primary key (id),
  constraint landmark_image_contentid_serialnum_unique unique (contentid, serialnum),
  constraint landmark_image_contentid_fk foreign KEY (contentid) references landmark (contentid) on delete CASCADE
) TABLESPACE pg_default;
CREATE TABLE public.landmark_intro (
  contentid bigint NOT NULL,
  contenttypeid integer NOT NULL,
  heritage1 boolean DEFAULT false,
  heritage2 boolean DEFAULT false,
  heritage3 boolean DEFAULT false,
  infocenter text,
  opendate text,
  restdate text,
  expguide text,
  expagerange text,
  accomcount text,
  useseason text,
  usetime text,
  parking text,
  chkbabycarriage boolean DEFAULT false,
  chkpet boolean DEFAULT false,
  chkcreditcard boolean DEFAULT false,
  CONSTRAINT landmark_intro_pkey PRIMARY KEY (contentid),
  CONSTRAINT landmark_intro_contentid_fk FOREIGN KEY (contentid) REFERENCES public.landmark(contentid)
);
CREATE TABLE public.region_sigungu_map (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  area_code integer NOT NULL,
  sigungu_code integer NOT NULL,
  sigungu_name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  sido_name text NOT NULL DEFAULT ''::text,
  CONSTRAINT region_sigungu_map_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text,
  nickname text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);