-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.region_sigungu_map (
  id bigint generated by default as identity not null,
  area_code integer not null,
  sigungu_code integer not null,
  sigungu_name text not null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  sido_name text not null default ''::text,
  constraint region_sigungu_map_pkey primary key (id),
  constraint region_sigungu_map_area_code_sigungu_code_key unique (area_code, sigungu_code),
  constraint region_sigungu_map_area_code_sigungu_name_key unique (area_code, sigungu_name)
) TABLESPACE pg_default;